name: ci/cd Pipeline
on:
  push:
    branches: [main]
jobs:
  build:
    name: build and cache docker image
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and cache image (GHCR)
        uses: docker/build-push-action@v5
        id: docker_build_push
        with:
          context: .
          file: ./Dockerfile
          target: chatserver-final
          push: false
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/chatserver-final:cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}/chatserver-final:cache,mode=max
          tags: ghcr.io/${{ github.repository }}/chatserver-final:latest
